### ISSUE TITLE
Suggestion to translate into russian

### ISSUE THREAD

**Issue by RinatValiullov** [FAQGURU/FAQGURU#1]
Почему на русском не сделали сразу как вторую ветку, скажем? Было бы замечательно чтобы и другие разработчики, кто не понимает или плохо понимает на английском смогли работать с этими вопросами.

Why didn't you do it in Russian right away as a second branch, let's say? It would be great if other developers who do not understand or understand English poorly could work with these questions.

**Comment by js2me** [comment]
Sounds a great idea, I think that russian which have a good English should create pull request to the new branch.
I can try to help with this

**Comment by RinatValiullov** [comment]
> Sounds a great idea, I think that russian which have a good English should create pull request to the new branch.
> I can try to help with this

Can other people extend this set? Add more questions or even another topic?

**Comment by uliaaan** [comment]
@RinatValiullov @js2me Hey, guys! We are glad that you loved our repo. Unfotunatly we have other goals. We have over 20 topics in our todo list that is around 2000+ questions. But you can make translation for any language yourself (there is a description in readme). Thank you for your support!
