### ISSUE TITLE
Translation of the topic about JavaScript into Russian

### ISSUE THREAD

**Issue by lex111** [FAQGURU/FAQGURU#6]
Hello @denisschmidt and @uliaaan! 

I prepared everything is necessary as described here https://github.com/FAQGURU/FAQGURU/blob/master/CONTRIBUTING.md#Translations

My repo for transfer - https://github.com/lex111/FAQGURU
Language - JavaScript and more maybe

**Comment by uliaaan** [comment]
#20

**Comment by lex111** [comment]
Why is it closed? Written in the guide that need a separate repository, is not it?

**Comment by lex111** [comment]
Мда, ладно, буду переводить в собственном форке, а то у вас большие проблемы с обратной связью, да и существующий русский перевод JS-темы через гугл-переводчик, так себе.
